import { Providers } from "./Providers";

export const metadata = {
  title: "The Wedding of Nailal & Via by Invitato",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
